### ISSUE TITLE
Remedial work

### ISSUE THREAD

**Issue by ckiss** [senecajs/seneca-linkedin-auth#1]
- [x] update dependencies
- [x] update linting to match https://github.com/mirceaalexandru/seneca-local-auth
- [x] fix linting errors
- [x] remove any uneeded dependencies
- [x] Update license comment to match seneca-local-auth style
- [x] Add annotations as per seneca-local-auth
- [x] Update readme to say we have annotations like https://github.com/senecajs/seneca-rabbitmq-transport
- [x] add .gitignore like seneca-local-auth

**Comment by ghost** [comment]
Is this completed?

**Comment by ckiss** [comment]
@matt-oc are all this points covered? If so, please let me know and I'll close it

**Comment by matt-oc** [comment]
@ckiss yep all done!
